name: AbgabeThamarVainstain

author: Halatira
webside:
main: Main
version: 0.8

commands:
     Tunnel:
        description: Create a secret tunnel
        usage: /Tunnel
     FortuneWheel:
        description: Create and use a fortunewheel
        usage: /FortueWheel




